CREATE TABLE password_reset_tokens (
    token_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR2(128) NOT NULL UNIQUE,
    user_id NUMBER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_password_reset_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
);
