package com.rev.app.config;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;

@Slf4j
@Configuration
public class DatabaseSchemaInitializer {

    @Bean
    ApplicationRunner ensureDatabaseSchema(JdbcTemplate jdbcTemplate) {
        return args -> {
            String imageColumnSql = """
                    BEGIN
                        EXECUTE IMMEDIATE 'ALTER TABLE products ADD image_url VARCHAR2(500)';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -1430 THEN
                                RAISE;
                            END IF;
                    END;
                    """;
            jdbcTemplate.execute(imageColumnSql);
            log.info("Ensured products.image_url column exists");

            String resetTokenTableSql = """
                    BEGIN
                        EXECUTE IMMEDIATE '
                            CREATE TABLE password_reset_tokens (
                                token_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                token VARCHAR2(128) NOT NULL UNIQUE,
                                user_id NUMBER NOT NULL,
                                created_at TIMESTAMP NOT NULL,
                                expires_at TIMESTAMP NOT NULL,
                                used NUMBER(1) DEFAULT 0 NOT NULL,
                                CONSTRAINT fk_password_reset_user
                                    FOREIGN KEY (user_id)
                                    REFERENCES users(user_id)
                            )
                        ';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN
                                RAISE;
                            END IF;
                    END;
                    """;
            jdbcTemplate.execute(resetTokenTableSql);
            log.info("Ensured password_reset_tokens table exists");
        };
    }
}
